In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [2]:
url = 'https://raw.githubusercontent.com/IBM/telco-customer-churn-on-icp4d/master/data/Telco-Customer-Churn.csv'
df = pd.read_csv(url)

In [3]:
obj_cols = df.select_dtypes(include='object').columns.to_list()
print(f"Total: {len(obj_cols)}")
print(obj_cols)

Total: 18
['customerID', 'gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'TotalCharges', 'Churn']

In [4]:
df['gender'].value_counts()

gender
Male      3555
Female    3488
Name: count, dtype: int64

In [5]:
dummies = pd.get_dummies(df['InternetService'], prefix='Internet')
print(dummies.shape)
print(dummies.head())

(7043, 3)
   Internet_DSL  Internet_Fiber optic  Internet_No
0          True                 False        False
1          True                 False        False
2          True                 False        False
3          True                 False        False
4         False                  True        False

In [6]:
dummies_2 = pd.get_dummies(df['InternetService'], prefix='Internet', drop_first=True)
print(dummies_2.shape)
print(dummies_2.head())

(7043, 2)
   Internet_Fiber optic  Internet_No
0                 False        False
1                 False        False
2                 False        False
3                 False        False
4                  True        False

In [7]:
encoder = OneHotEncoder(sparse_output=False)
encoded = encoder.fit_transform(df[['TechSupport']])
encoded_df = pd.DataFrame(encoded, columns=encoder.get_feature_names_out(['TechSupport']))
encoded_df.head()

   TechSupport_No  TechSupport_No internet service  TechSupport_Yes
0             1.0                              0.0              0.0
1             1.0                              0.0              0.0
2             1.0                              0.0              0.0
3             0.0                              0.0              1.0
4             1.0                              0.0              0.0

In [8]:
df['Partner_bin'] = df['Partner'].map({'No': 0, "Yes": 1})
df[['Partner', 'Partner_bin']].head()

  Partner  Partner_bin
0     Yes            1
1      No            0
2      No            0
3      No            0
4      No            0

In [9]:
multi = pd.get_dummies(df[['gender', 'InternetService', 'TechSupport', 'Contract']], drop_first=True)
print(multi.shape)
multi.head()

(7043, 7)

,gender_Male,InternetService_Fiber optic,InternetService_No,TechSupport_No internet service,TechSupport_Yes,Contract_One year,Contract_Two year
0,False,False,False,False,False,False,False
1,True,False,False,False,False,True,False
2,True,False,False,False,False,False,False
3,True,False,False,False,True,True,False
4,False,True,False,False,False,False,False